language: objective-c
osx_image: xcode7.3
xcode_project: SUSwiftSugar.xcodeproj
xcode_scheme: SUSwiftSugar
env:
  global:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6s"
  - FRAMEWORK_NAME="SUSwiftSugar"
branches:
  only:
  - master
  - develop
  - "/^v?[0-9\\.]+/"
before_install:
- brew update
script:
- set -o pipefail
- xcodebuild test -project "$TRAVIS_XCODE_PROJECT" -scheme "$TRAVIS_XCODE_SCHEME" -configuration Release -sdk appletvsimulator -destination "$DESTINATION" | xcpretty -c
before_deploy:
- carthage build --no-skip-current
- carthage archive "$FRAMEWORK_NAME"
deploy:
  provider: releases
  api_key:
    secure: YdlmchubknV6LUMZFJcqk5koC7a2Hy/LDXbXhAxstpKXY1ePYootDpaAqMee6Y5R+angy8J8jlg2blOlplGor782gUePzBfNKqS4rA0Yc2N7WrhEy0WmbtfElw+vQRph/9xaNDsOTU97zzt0Xhkikkyg++ZsnjMP+RDUPGc+U3aXO8lDai8cj5Vk10yQe6TAVf7jQ0lr4wxyQX8OD+OiYouEmG6fKsInGhz+DUvBcQERr2gg38yDi8c7MhuKgsN2oAd2HET6hdJSKhFXbpn0PAQjpjXNhess8m8kGAAe1UTU5MuWzjG5eyXXhxz/HOzL0Wh+OA+8QOOCY+qcotmvpGgfl2sbjukDC8jRpX/NgaLX2Lq54RtmniZsP5QzsKy3VpgJERTdLOT9WLXOC9PAU2+KR88G2rpiiBRy8M4L9wwWZyYFxqweCjdL7MJQc4f00lmXaNnV/XxK75ZWcT4aZ323tbTHjuJwEtQVLbK9ORGW+45VdoBDVnsfdVswRHJDDTO4pLy31Qx2mU8NwUmrr8qtjTAbu6x00FEllyjqih25Tkn41R9c2/yzAz2zBOLUc5KCcmPAZ1gOLHChwKx3AZB2758phuB2jhCdc60NwTVSSpW7zf3LzF/n65/sHDw3TUk5EbE4NIJuxUBjlE3Ond/BCbuktntPBqIG4kCyzSE=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: "$TRAVIS_REPO_SLUG"
    tags: true
notifications:
  email: false
  slack:
    secure: MBfMwq5TnFCYeUdEc+NvZBIHYv5QaeoCsnUrpJGopQOtcgV3nclkl3KvQkvnb6yJ4l5osfC5tSOJccc8Qy79BQwxSpYeEptbMZsu+92K36oBb7ivuQgp9+bO1Oa4PiatwOmbUJHG64+0hYwTwmaGFzabQUijy3mRCgRrJPtRj9s6wAZL16LifbQIptXdmyIq2JD5NOEpT5EsJ3VCp68QkjrZcDd8cjsm9Mn/rnuPsALgIL1NO5RIBjs+AVdJR+3VulYsZJ/UFja2K2k9g16GwxGA/eGjy8NPBl/3lxkbnmCVrdQGB2rnHPN7E7BaKZ/+j0VgCR+fj/ArDha3LzKM1tTvraKhN7ASa5XRTBv08Ou4c5xPJ1XuV0/x5hVOktD9iXXLbnxc4VT5kJNCOpur9rMvu9bpL+3T2MbibC/gj5sydVM5xzmkXXQb/r5+nkLg1RneX3s0Jq+hf5vT5Ouw+oMzQbYDa5qewZRESazBcsiRlNU092RweoDR3sctgahtERJFZVEYcsjEfQaN1PrbiA6Dg898QDSp5bbHaVWSLqrOWqkkEYo1VMTORsMiB1MVtac3l5W/g38WL44fu/cchbOnFNcvK/VoL7FyyRpyX7QyQ1oUXG/oDgcAegatCHuJb0YwEj7oV9NviYsRaYBrLdZhtLEqzuOUic7rsXxA8is=
